### ISSUE TITLE
使用的JDK 1.8 Error: VM option 'UseG1GC' is experimental and must be enabled via -XX:+UnlockExperimentalVMOptions. Error: Could not create the Java Virtual Machine. Error: A fatal exception has occurred. Program will exit.

### ISSUE THREAD

**Issue by addxing** [tp7309/TTDeDroid#11]
使用的JDK 1.8
Error: VM option 'UseG1GC' is experimental and must be enabled via -XX:+UnlockExperimentalVMOptions.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by tp7309** [comment]
fix done, please use latest version.
