### ISSUE TITLE
加固的能反编译？

### ISSUE THREAD

**Issue by AndMy** [tp7309/TTDeDroid#4]
加固的能反编译？

**Comment by tp7309** [comment]
发个示例APP地址过来呗，不能的话再想办法支持。

**Comment by AndMy** [comment]
> 发个示例APP地址过来呗，不能的话再想办法支持。

http://dx2.anxz.com/soft/c/com.uniview.app.smb.phone.en.ezview.apk

这个

**Comment by tp7309** [comment]
不支持，可以找找全网的apk脱壳方案。例如这种：
https://github.com/WrBug/DeveloperHelper
