### ISSUE TITLE
执行出错

### ISSUE THREAD

**Issue by HeyAragon** [tp7309/TTDeDroid#5]
mac  执行之后出现这个   zsh: /Users/hh/Documents/TTDeDroid/bin/showjar: bad interpreter: /bin/sh^M: no such file or directory

**Comment by tp7309** [comment]
可以按这个[文章](https://www.jianshu.com/p/5ae6d4a273b8)处理一下，看是否可以生效：
```bash
vim ~/Documents/TTDeDroid/bin/showjar
```
