### ISSUE TITLE
line 5: python: command not found

### ISSUE THREAD

**Issue by southbaird** [tp7309/TTDeDroid#6]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/24732032/166878883-59b6af43-098e-4ba7-bc76-6751abb26345.png">

**Comment by southbaird** [comment]
版本 v1.3.1

**Comment by tp7309** [comment]
Mac吗，如果机器上没有就安装一个：
[安装python教程](https://www.liaoxuefeng.com/wiki/1016959663602400/1016959856222624)

**Comment by southbaird** [comment]
@tp7309 python 有的 v3.9.1

**Comment by tp7309** [comment]
你执行下`python --version`看有打印python版本号吗，如果没有的话那就是python命令不对。
可能不是python而是python3，如果`python3 --version`有显示版本号的话，把`/bin/showjar`那文件中的`python`替换成`python3`。
