### ISSUE TITLE
执行命令之后，一直报虚拟机异常这样的错误

### ISSUE THREAD

**Issue by YubaKevin** [tp7309/TTDeDroid#7]
![image](https://user-images.githubusercontent.com/22018498/167447310-09960f87-82b4-4b5f-962c-3ee6c078637a.png)

**Comment by tp7309** [comment]
jadx启动失败了，内存不足。java什么版本？电脑是64位的吗？
直接点击`TTDeDroid\libs\jadx\bin\jadx-gui.bat`看能启动不。

**Comment by skr-rks** [comment]
请问下，我直接运行jadx-gui.bat也是这个报错。但是本机装的jadx单独打开就没有这个报错，64电脑。java版本1.8.0_181

**Comment by tp7309** [comment]
可能是内存不足，在`jadx-gui.bat`的下面这行代码中，增加个 **-Xmx2048M** 的参数，增加下最大可用内存试试：

```
set DEFAULT_JVM_OPTS="-Xms128M" "-Xmx2048M" "-XX:MaxRAMPercentage=70.0" "-XX:+UseG1GC" "-Dawt.useSystemAAFontSettings=lcd" "-Dswing.aatext=true"
```

**Comment by molixiaoge** [comment]
一样的错误，java version "1.8.0_111"

**Comment by tp7309** [comment]
> 可能是内存不足，在`jadx-gui.bat`的下面这行代码中，增加个 **-Xmx2048M** 的参数，增加下最大可用内存试试：
> 
> ```
> set DEFAULT_JVM_OPTS="-Xms128M" "-Xmx2048M" "-XX:MaxRAMPercentage=70.0" "-XX:+UseG1GC" "-Dawt.useSystemAAFontSettings=lcd" "-Dswing.aatext=true"
> ```

@molixiaoge 有试验这个方法吗

**Comment by molixiaoge** [comment]
@tp7309 

设置了jadx-gui.bat 里面的 
`set DEFAULT_JVM_OPTS="-Xms128M" "-Xmx2048M" "-XX:MaxRAMPercentage=70.0" "-XX:+UseG1GC" "-Dawt.useSystemAAFontSettings=lcd" "-Dswing.aatext=true"` 启动还是报错。

后来我删除启动参数，发现只要删掉 `"-XX:MaxRAMPercentage=70.0"` 即可启动成功，启动参数如下
`set DEFAULT_JVM_OPTS="-Xms128M" "-XX:+UseG1GC"  "-Dawt.useSystemAAFontSettings=lcd" "-Dswing.aatext=true" "-Djava.util.Arrays.useLegacyMergeSort=true"`

说明和jdk的版本有关，版本信息如下


java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
